getscu:
    image: dcm4che
    net: ncwork
    hostname: getscu
    container_name: getscu
    volumes:
      - /home/roger/Documents/Projects/dcm4che/replicas:/home/client/replicas
      - /home/roger/Documents/Projects/dcm4che/results:/home/client/results
    command: "./query.sh 10"

