storescu:
    image: dcm4che
    net: ncwork
    hostname: storescu
    container_name: storescu
    volumes:
      - /home/roger/Documents/Projects/dcm4che/results:/home/client/results
    command: "./client.sh 10"